### ISSUE TITLE
Load market bug

### ISSUE THREAD

**Issue by allanburleson** [V1Soft/textbasedgame#15]
When I saves and quits while in the market, when I return I get this error:

```
Traceback (most recent call last):
  File "./textbasedgame.py", line 538, in <module>
    play()
  File "./textbasedgame.py", line 500, in play
    loadGame()
  File "./textbasedgame.py", line 469, in loadGame
    goToVendor(player.location.entity)
  File "./textbasedgame.py", line 251, in goToVendor
    print('%s\nItems for sale:' % vendor.message)
AttributeError: 'NoneType' object has no attribute 'message'

```

I can't figure out why it thinks the vendor is of NoneType.

**Comment by allanburleson** [comment]
Fixed.
