### ISSUE TITLE
Savefile broken *again*

### ISSUE THREAD

**Issue by allanburleson** [V1Soft/textbasedgame#19]
Surprise, surprise...someone broke the savefile _again_

```
pi@raspberrypi:~/textbasedgame $ ./textbasedgame.py 

+----------------------------------------------+
| Welcome to textbasedgame!                    |
| This game is released under the GPL.         |
| Copyright V1Soft 2016                        |
+----------------------------------------------+

Do you want to:
1. Start a new game (new)
2. Continue from a previous save (continue) or
3. Exit the game (quit)
: 2
List of users:
1. test
What is your username? : bob
Invalid Choice.
What is your username? : ^C
+----------------------------------------------+
| Welcome to textbasedgame!                    |
| This game is released under the GPL.         |
| Copyright V1Soft 2016                        |
+----------------------------------------------+

Do you want to:
1. Start a new game (new)
2. Continue from a previous save (continue) or
3. Exit the game (quit)
: 1
What is your desired username? : bob
New game set up. Welcome.
: quit
Are you sure you want to quit? (Y/n) 

Saving progress...
Progress saved.
pi@raspberrypi:~/textbasedgame $ ./textbasedgame.py 

+----------------------------------------------+
| Welcome to textbasedgame!                    |
| This game is released under the GPL.         |
| Copyright V1Soft 2016                        |
+----------------------------------------------+

Do you want to:
1. Start a new game (new)
2. Continue from a previous save (continue) or
3. Exit the game (quit)
: 2
List of users:
1. test
What is your username? : test
Traceback (most recent call last):
  File "./textbasedgame.py", line 121, in <module>
    play()
  File "./textbasedgame.py", line 104, in play
    loadGame()
  File "./textbasedgame.py", line 72, in loadGame
    entities.worldEntities = utils.loadInfo(usr, 'worldEntities')
  File "/home/pi/textbasedgame/utils.py", line 213, in loadInfo
    saveFile = shelve.open(fileDir + '/saves/%s.save' % username)
  File "/usr/lib/python3.4/shelve.py", line 239, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.4/shelve.py", line 223, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.4/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
```

**Comment by ghost** [comment]
I've noticed this too, and thus stayed away from the test profile.

**Comment by ghost** [comment]
I don't know how to fix this, why am I the assignee?

**Comment by ghost** [comment]
This specific problem is caused by the list of entities being changed from 'entities' to 'worldEntities', just recreate the test profile.

**Comment by allanburleson** [comment]
Sorry, I didn't copy the whole thing. When I try to load a newer save I just made, it tells me that it's broken.

**Comment by allanburleson** [comment]
You're the assignee because you changed it and now it doesn't work. I'm not sure exactly what's different, so it would probably be easier for you to do it.

**Comment by ghost** [comment]
it works for me

**Comment by ghost** [comment]
I'm obviously not a developer, I'm a _de_developer

**Comment by allanburleson** [comment]
Well, I fixed it. I figured out the problem.
