### ISSUE TITLE
Cannot exit game

### ISSUE THREAD

**Issue by ghost** [V1Soft/textbasedgame#5]
"quitGame()" seems to be the error at "sys.exit()"
I am working on solution.

KeyboardInterrupt
^CFatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 762, in get_code
  File "<frozen importlib._bootstrap_external>", line 473, in _compile_bytecode
KeyboardInterrupt
^C^C^C^CFailed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/usr/lib/python3.5/os.py", line 768, in <module>
    environ = _createenviron()
  File "/usr/lib/python3.5/os.py", line 753, in _createenviron
    encoding = sys.getfilesystemencoding()
KeyboardInterrupt
^CFatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.5/io.py", line 52, in <module>
    import abc
  File "/usr/lib/python3.5/abc.py", line 234, in <module>
    class ABC(metaclass=ABCMeta):
  File "/usr/lib/python3.5/abc.py", line 146, in __new__
    cls._abc_cache = WeakSet()
  File "/usr/lib/python3.5/_weakrefset.py", line 48, in __init__
^C^CPrevious game save loaded.
Type "help" for help.
: quit
Are you sure you want to quit? Your progress will be saved.
y
Saving progress...
Progress saved.
Previous game save loaded.
Type "help" for help.

**Comment by allanburleson** [comment]
I am unable to reproduce this. Maybe your sys module is messed up
